source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.3'
use_frameworks!

target 'ExtendedUINavigationBar_Example' do
  pod 'ExtendedUINavigationBar', :path => '../'

  target 'ExtendedUINavigationBar_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.4'
    pod 'iOSSnapshotTestCase' , '~> 6.2.0'
    pod 'Nimble-Snapshots' , '~> 8.0.0'
  end
end
